# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_adress', models.CharField(max_length=140, verbose_name='адрес для карты')),
                ('adress', models.CharField(max_length=154, verbose_name='адрес')),
                ('email', models.CharField(max_length=42, verbose_name='email')),
                ('phone', models.CharField(max_length=21, verbose_name='телефон')),
                ('slogan', models.CharField(blank=True, max_length=700, verbose_name='Девиз')),
            ],
            options={
                'verbose_name_plural': 'Контактная инфа',
                'verbose_name': 'Контактная инфа',
            },
        ),
        migrations.CreateModel(
            name='MetaTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70, verbose_name='Заголовок сайта (тэг <title>, до 70 символов)')),
                ('keywords', models.CharField(blank=True, max_length=210, verbose_name='Ключевые слова через запятую (тэг <keywords>, до 210 символов)')),
                ('description', models.CharField(blank=True, max_length=210, verbose_name='Описание (тэг <keywords>, до 210 символов)')),
            ],
            options={
                'verbose_name_plural': 'Метатэги',
                'verbose_name': 'Метатэги',
            },
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=70, verbose_name='Ссылка на facebook')),
                ('twitter', models.CharField(blank=True, max_length=70, verbose_name='Ссылка на twitter')),
                ('instagram', models.CharField(blank=True, max_length=70, verbose_name='Ссылка на instagram')),
                ('behance', models.CharField(blank=True, max_length=70, verbose_name='Ссылка на behance')),
                ('dribble', models.CharField(blank=True, max_length=70, verbose_name='Ссылка на dribble')),
            ],
            options={
                'verbose_name_plural': 'Ссылки на соц. сайты',
                'verbose_name': 'Ссылки на соц. сайты',
            },
        ),
    ]
