# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контактная инфа', 'verbose_name_plural': 'Контактная инфа'},
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='longitude',
        ),
        migrations.AddField(
            model_name='contacts',
            name='adress',
            field=models.CharField(default=1, max_length=154, verbose_name='адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.CharField(default=1, max_length=42, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='map_adress',
            field=models.CharField(default=1, max_length=140, verbose_name='адрес для карты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone',
            field=models.CharField(default=1, max_length=21, verbose_name='телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='slogan',
            field=models.CharField(blank=True, max_length=700, verbose_name='Девиз'),
        ),
    ]
