# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20160518_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контактная инфа', 'verbose_name_plural': '1: Контактная инфа'},
        ),
        migrations.AlterModelOptions(
            name='metatags',
            options={'verbose_name': 'Метатэги', 'verbose_name_plural': '3: Метатэги'},
        ),
        migrations.AlterModelOptions(
            name='sociallinks',
            options={'verbose_name': 'Ссылки на соц. сайты', 'verbose_name_plural': '2: Ссылки на соц. сайты'},
        ),
    ]
