# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20160501_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.CharField(default=0, max_length=42, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='map_adress',
            field=models.CharField(default=0, max_length=140, verbose_name='map_adress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone',
            field=models.CharField(default=123456, max_length=14, verbose_name='adress'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacts',
            name='adress',
            field=models.CharField(max_length=154, verbose_name='adress'),
        ),
    ]
