# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-16 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20160518_1521'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetaTags',
        ),
    ]
