# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20160501_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(max_length=21, verbose_name='phone'),
        ),
    ]
