# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20160511_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контактная инфа', 'verbose_name_plural': 'Контактная инфа'},
        ),
    ]
