# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 15:31
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='works/instance')),
                ('i_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['i_order'],
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_image', models.ImageField(upload_to='blog/top_image')),
                ('title', models.CharField(max_length=49)),
                ('slogan', models.CharField(blank=True, max_length=140)),
                ('block1', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, upload_to='')),
                ('block2', models.TextField(blank=True)),
                ('image2', models.ImageField(blank=True, upload_to='')),
                ('block3', models.TextField(blank=True)),
                ('image3', models.ImageField(blank=True, upload_to='')),
                ('tags', models.CharField(blank=True, max_length=140)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='carousel',
            name='post',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
