# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmetatags',
            name='description',
            field=models.CharField(blank=True, max_length=210, verbose_name='Описание (тэг <description>, до 210 символов)'),
        ),
    ]
