# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 19:28
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Bottom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(blank=True, max_length=35)),
                ('h2', models.CharField(blank=True, max_length=35)),
                ('h3', models.CharField(blank=True, max_length=35)),
                ('text', models.TextField(blank=True)),
                ('blockquote', models.TextField(blank=True)),
                ('cite', models.CharField(blank=True, max_length=35)),
                ('video', models.CharField(blank=True, max_length=35)),
                ('image', models.ImageField(blank=True, upload_to='blog/block')),
                ('b_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Нижние блоки, которые под каруселью',
                'ordering': ['b_order'],
                'verbose_name': 'Нижний блок',
            },
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(blank=True, max_length=35)),
                ('h2', models.CharField(blank=True, max_length=35)),
                ('h3', models.CharField(blank=True, max_length=35)),
                ('text', models.TextField(blank=True)),
                ('blockquote', models.TextField(blank=True)),
                ('cite', models.CharField(blank=True, max_length=35)),
                ('video', models.CharField(blank=True, max_length=35)),
                ('image', models.ImageField(blank=True, upload_to='blog/block')),
                ('top_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Верхние блоки, которые над каруселью',
                'ordering': ['top_order'],
                'verbose_name': 'Верхний блок',
            },
        ),
        migrations.CreateModel(
            name='TopMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_image', models.ImageField(upload_to='blog/media')),
                ('title', models.CharField(blank=True, max_length=49)),
                ('slogan', models.CharField(blank=True, max_length=140)),
            ],
        ),
        migrations.AlterModelOptions(
            name='carousel',
            options={'ordering': ['i_order'], 'verbose_name': 'Картинка 1000 на 600', 'verbose_name_plural': 'Картинки для карусели 1000 на 600'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['post_order'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='block1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='block2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image3',
        ),
        migrations.AddField(
            model_name='post',
            name='middle_background',
            field=models.ImageField(default=1, upload_to='blog/middle_bg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(upload_to='blog/instance/carousel'),
        ),
        migrations.AddField(
            model_name='top',
            name='post',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AddField(
            model_name='bottom',
            name='post',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
