# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 14:40
from __future__ import unicode_literals

import adminsortable.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=140, verbose_name='Тэги через "," без пробелов')),
            ],
            options={
                'verbose_name_plural': 'Тэги для подменю',
                'verbose_name': 'Тэги для подменю',
            },
        ),
        migrations.CreateModel(
            name='Bottom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст')),
                ('video', models.CharField(blank=True, max_length=14, verbose_name='Видео ID(youtube)')),
                ('image', models.ImageField(blank=True, upload_to='blog/block', verbose_name='Картинка')),
                ('b_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['b_order'],
                'verbose_name_plural': 'Нижние блоки, которые под каруселью',
                'verbose_name': 'Нижний блок',
            },
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст')),
                ('video', models.CharField(blank=True, max_length=14, verbose_name='Видео ID(youtube)')),
                ('image', models.ImageField(blank=True, upload_to='blog/block', verbose_name='Картинка')),
                ('top_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['top_order'],
                'verbose_name_plural': 'Верхние блоки, которые над каруселью',
                'verbose_name': 'Верхний блок',
            },
        ),
        migrations.CreateModel(
            name='TopMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_image', models.ImageField(upload_to='blog/media', verbose_name='Картинка 1600 на 1060')),
                ('title', models.CharField(blank=True, max_length=49, verbose_name='Заголвок')),
                ('slogan', models.CharField(blank=True, max_length=140, verbose_name='Девиз')),
            ],
            options={
                'verbose_name_plural': 'Заставка для блога',
                'verbose_name': 'Заставка для блога',
            },
        ),
        migrations.AlterModelOptions(
            name='carousel',
            options={'ordering': ['i_order'], 'verbose_name': 'Картинка 1000 на 600', 'verbose_name_plural': 'Картинки для карусели 1000 на 600'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['post_order'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='block1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='block2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='block3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image3',
        ),
        migrations.AddField(
            model_name='post',
            name='post_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='txt',
            field=models.TextField(blank=True, verbose_name='Предварительный текст'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(upload_to='blog/instance/carousel'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slogan',
            field=models.CharField(blank=True, max_length=140, verbose_name='Девиз'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=140, verbose_name='Тэги через "," без пробелов'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=49, verbose_name='Заголовок заставки'),
        ),
        migrations.AlterField(
            model_name='post',
            name='top_image',
            field=models.ImageField(upload_to='blog/top_image', verbose_name='Заставка'),
        ),
        migrations.AddField(
            model_name='top',
            name='post',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AddField(
            model_name='bottom',
            name='post',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
