# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['post_order'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='post_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
