# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160510_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottom',
            name='blockquote',
        ),
        migrations.RemoveField(
            model_name='top',
            name='blockquote',
        ),
    ]
