# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 17:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160505_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='middle_background',
            field=models.ImageField(default=datetime.datetime(2016, 5, 5, 17, 5, 44, 217827, tzinfo=utc), upload_to='blog/middle_bg'),
            preserve_default=False,
        ),
    ]
