# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogmetatags_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alltags',
            options={'verbose_name': 'Тэги для подменю', 'verbose_name_plural': '2: Тэги для подменю'},
        ),
        migrations.AlterModelOptions(
            name='blogmetatags',
            options={'verbose_name': 'МетаТэги', 'verbose_name_plural': '4: МетаТэги'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['post_order'], 'verbose_name': 'Пост', 'verbose_name_plural': '3: Посты'},
        ),
        migrations.AlterModelOptions(
            name='topmedia',
            options={'verbose_name': 'Заставка для блога', 'verbose_name_plural': '1: Заставка для блога'},
        ),
    ]
