# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160510_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottom',
            name='blockquote',
            field=models.CharField(blank=True, max_length=420),
        ),
        migrations.AddField(
            model_name='top',
            name='blockquote',
            field=models.CharField(blank=True, max_length=420),
        ),
    ]
