# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alltags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.CharField(default=0, max_length=21),
            preserve_default=False,
        ),
    ]
