# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160510_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='block3',
        ),
        migrations.AddField(
            model_name='post',
            name='txt',
            field=models.TextField(blank=True, verbose_name='Предварительный текст'),
        ),
    ]
