# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160510_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='middle_background',
            field=models.ImageField(upload_to='blog/middle_bg', verbose_name='Доп. заставка'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slogan',
            field=models.CharField(blank=True, max_length=140, verbose_name='Девиз'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=140, verbose_name='Тэги через "," без пробелов'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=49, verbose_name='Заголовок заставки'),
        ),
        migrations.AlterField(
            model_name='post',
            name='top_image',
            field=models.ImageField(upload_to='blog/top_image', verbose_name='Заставка'),
        ),
    ]
