# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 16:42
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160510_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='middle_background',
        ),
        migrations.RemoveField(
            model_name='top',
            name='blockquote',
        ),
        migrations.RemoveField(
            model_name='top',
            name='cite',
        ),
        migrations.RemoveField(
            model_name='top',
            name='h1',
        ),
        migrations.RemoveField(
            model_name='top',
            name='h2',
        ),
        migrations.RemoveField(
            model_name='top',
            name='h3',
        ),
        migrations.AlterField(
            model_name='top',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
