# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160511_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottom',
            name='video',
            field=models.CharField(blank=True, max_length=14, verbose_name='Видео ID(youtube)'),
        ),
        migrations.AlterField(
            model_name='top',
            name='video',
            field=models.CharField(blank=True, max_length=14, verbose_name='Видео ID(youtube)'),
        ),
    ]
