# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160512_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alltags',
            options={'verbose_name': 'Тэги для подменю', 'verbose_name_plural': 'Тэги для подменю'},
        ),
        migrations.AlterField(
            model_name='alltags',
            name='tags',
            field=models.CharField(max_length=140, verbose_name='Тэги через "," без пробелов'),
        ),
    ]
