# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20160512_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topmedia',
            options={'verbose_name': 'Заставка для блога', 'verbose_name_plural': 'Заставка для блога'},
        ),
        migrations.AlterField(
            model_name='topmedia',
            name='slogan',
            field=models.CharField(blank=True, max_length=140, verbose_name='Девиз'),
        ),
        migrations.AlterField(
            model_name='topmedia',
            name='title',
            field=models.CharField(blank=True, max_length=49, verbose_name='Заголвок'),
        ),
        migrations.AlterField(
            model_name='topmedia',
            name='top_image',
            field=models.ImageField(upload_to='blog/media', verbose_name='Картинка 1600 на 1060'),
        ),
    ]
