# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_image', models.ImageField(upload_to='')),
                ('name', models.CharField(default='', max_length=49)),
                ('slogane', models.CharField(default='', max_length=49)),
                ('top_title', models.CharField(default='', max_length=49)),
                ('top_description_italic', models.TextField()),
                ('top_description', models.TextField()),
                ('video_id', models.CharField(default='', max_length=49)),
                ('midlle_title', models.CharField(default='', max_length=49)),
                ('middle_description', models.TextField()),
                ('bottom_title', models.CharField(default='', max_length=49)),
                ('bottom_description', models.TextField()),
                ('client', models.CharField(default='', max_length=49)),
                ('tags', models.CharField(default='', max_length=70)),
                ('the_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['the_order'],
                'verbose_name_plural': 'GameObj',
                'verbose_name': 'GameObj',
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.Game')),
            ],
        ),
    ]
