# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 12:52
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='bottom_description',
        ),
        migrations.RemoveField(
            model_name='work',
            name='bottom_title',
        ),
        migrations.RemoveField(
            model_name='work',
            name='middle_description',
        ),
        migrations.RemoveField(
            model_name='work',
            name='midlle_title',
        ),
        migrations.RemoveField(
            model_name='work',
            name='top_description',
        ),
        migrations.RemoveField(
            model_name='work',
            name='top_description_italic',
        ),
        migrations.RemoveField(
            model_name='work',
            name='top_title',
        ),
        migrations.AddField(
            model_name='work',
            name='text0',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Верхний текстовый блок'),
        ),
        migrations.AddField(
            model_name='work',
            name='text1',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Средний текстовый блок (под видео)'),
        ),
        migrations.AddField(
            model_name='work',
            name='text2',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Нижний текстовый блок (под каруселью)'),
        ),
        migrations.AlterField(
            model_name='work',
            name='slogan',
            field=models.CharField(blank=True, max_length=140, verbose_name='Девиз заставки'),
        ),
    ]
