# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20160512_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='bottom_description',
            field=models.TextField(blank=True, verbose_name='Текст 3 (под каруселью)'),
        ),
        migrations.AlterField(
            model_name='work',
            name='bottom_title',
            field=models.CharField(blank=True, max_length=49, verbose_name='Заголовок 3 (под каруселью)'),
        ),
        migrations.AlterField(
            model_name='work',
            name='middle_description',
            field=models.TextField(blank=True, verbose_name='Текст 2 (под видео)'),
        ),
        migrations.AlterField(
            model_name='work',
            name='midlle_title',
            field=models.CharField(blank=True, max_length=49, verbose_name='Заголовок 2 (под видео)'),
        ),
    ]
