# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_worksmetatags_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alltags',
            options={'verbose_name': 'Тэги для подменю', 'verbose_name_plural': '2: Тэги для подменю'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Заставка для работ', 'verbose_name_plural': '1: Заставка для работ'},
        ),
        migrations.AlterModelOptions(
            name='screenshot',
            options={'ordering': ['screenshot_order'], 'verbose_name': 'Картинка 1000 на 600', 'verbose_name_plural': 'Картинки карусели 1000 на 600'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['work_order'], 'verbose_name': 'Работа', 'verbose_name_plural': '3: Работы'},
        ),
        migrations.AlterModelOptions(
            name='worksmetatags',
            options={'verbose_name': 'МетаТэги', 'verbose_name_plural': '4: МетаТэги'},
        ),
        migrations.AlterField(
            model_name='work',
            name='preview_image',
            field=models.ImageField(upload_to='works/preview_images', verbose_name='Картинка для предпросмотра 800 на 600'),
        ),
        migrations.AlterField(
            model_name='work',
            name='top_image',
            field=models.ImageField(upload_to='works/top_images', verbose_name='Верхняя заставка-картинка 1600 на 1066'),
        ),
    ]
