# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 23:36
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='games/main_top_image', verbose_name='Top image 1000x600')),
                ('title', models.CharField(blank=True, max_length=49)),
                ('slogan', models.CharField(blank=True, max_length=140)),
            ],
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['game_order'], 'verbose_name': 'Game', 'verbose_name_plural': 'Game objects'},
        ),
        migrations.AlterModelOptions(
            name='screenshot',
            options={'ordering': ['screenshot_order'], 'verbose_name': 'ScreenShot', 'verbose_name_plural': 'ScreenShots'},
        ),
        migrations.RenameField(
            model_name='game',
            old_name='the_order',
            new_name='game_order',
        ),
        migrations.RemoveField(
            model_name='game',
            name='promo_image',
        ),
        migrations.RemoveField(
            model_name='game',
            name='slogane',
        ),
        migrations.RemoveField(
            model_name='screenshot',
            name='image',
        ),
        migrations.AddField(
            model_name='game',
            name='preview_image',
            field=models.ImageField(default=1, upload_to='games/preview_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='slogan',
            field=models.CharField(blank=True, max_length=49),
        ),
        migrations.AddField(
            model_name='game',
            name='top_image',
            field=models.ImageField(default=1, upload_to='games/top_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screenshot',
            name='screenshot_image',
            field=models.ImageField(default=1, upload_to='games/instance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screenshot',
            name='screenshot_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='bottom_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='bottom_title',
            field=models.CharField(blank=True, max_length=49),
        ),
        migrations.AlterField(
            model_name='game',
            name='client',
            field=models.CharField(blank=True, max_length=49),
        ),
        migrations.AlterField(
            model_name='game',
            name='middle_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='midlle_title',
            field=models.CharField(blank=True, max_length=49),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=49),
        ),
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='game',
            name='top_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='top_description_italic',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='top_title',
            field=models.CharField(blank=True, max_length=49),
        ),
        migrations.AlterField(
            model_name='game',
            name='video_id',
            field=models.CharField(blank=True, max_length=49),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='game',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
        ),
    ]
