# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20160508_0236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alltags',
            options={'verbose_name': 'Тэги для подменю', 'verbose_name_plural': 'Тэги для подменю'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['game_order'], 'verbose_name': 'Работа', 'verbose_name_plural': 'Работы'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Заставка для работ', 'verbose_name_plural': 'Заставка для работ'},
        ),
        migrations.AlterModelOptions(
            name='screenshot',
            options={'ordering': ['screenshot_order'], 'verbose_name': 'Картинка 1000 на 600', 'verbose_name_plural': 'Картинки 1000 на 600'},
        ),
        migrations.AlterField(
            model_name='alltags',
            name='tags',
            field=models.CharField(max_length=140, verbose_name='Тэги через "," без пробелов'),
        ),
        migrations.AlterField(
            model_name='game',
            name='bottom_description',
            field=models.TextField(blank=True, verbose_name='Текст 3'),
        ),
        migrations.AlterField(
            model_name='game',
            name='bottom_title',
            field=models.CharField(blank=True, max_length=49, verbose_name='Заголовок 3'),
        ),
        migrations.AlterField(
            model_name='game',
            name='client',
            field=models.CharField(blank=True, max_length=49, verbose_name='Для клиента: '),
        ),
        migrations.AlterField(
            model_name='game',
            name='middle_description',
            field=models.TextField(blank=True, verbose_name='Текст 2'),
        ),
        migrations.AlterField(
            model_name='game',
            name='midlle_title',
            field=models.CharField(blank=True, max_length=49, verbose_name='Заголовок 2'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=49, verbose_name='Название работы (крупное на заставке)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='preview_image',
            field=models.ImageField(upload_to='games/preview_images', verbose_name='Картинка предпросмотра 800 на 600'),
        ),
        migrations.AlterField(
            model_name='game',
            name='slogan',
            field=models.CharField(blank=True, max_length=49, verbose_name='Девиз заставки'),
        ),
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.CharField(blank=True, max_length=70, verbose_name='Тэги работы'),
        ),
        migrations.AlterField(
            model_name='game',
            name='top_description',
            field=models.TextField(blank=True, verbose_name='Текст 1'),
        ),
        migrations.AlterField(
            model_name='game',
            name='top_description_italic',
            field=models.TextField(blank=True, verbose_name='Текст - девиз (наклонный) 1'),
        ),
        migrations.AlterField(
            model_name='game',
            name='top_image',
            field=models.ImageField(upload_to='games/top_images', verbose_name='Картинка-заставка 1600 на 1066'),
        ),
        migrations.AlterField(
            model_name='game',
            name='top_title',
            field=models.CharField(blank=True, max_length=49, verbose_name='Заголовок 1'),
        ),
        migrations.AlterField(
            model_name='game',
            name='video_id',
            field=models.CharField(blank=True, max_length=49, verbose_name='Видео (код ютуба)'),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(upload_to='games/main_top_image', verbose_name='Картинка 1600 на 1060'),
        ),
        migrations.AlterField(
            model_name='media',
            name='slogan',
            field=models.CharField(blank=True, max_length=140, verbose_name='Девиз'),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(blank=True, max_length=49, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='screenshot_image',
            field=models.ImageField(upload_to='games/instance', verbose_name='Картинка 1000 на 600'),
        ),
    ]
