# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20160422_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='preview',
            new_name='preview_image',
        ),
    ]
