# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20160423_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenshot',
            old_name='image',
            new_name='screenshot_image',
        ),
    ]
