# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20160423_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='slogane',
            new_name='slogan',
        ),
    ]
