# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20160424_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='bottom_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='bottom_title',
            field=models.CharField(blank=True, default='', max_length=49),
        ),
        migrations.AlterField(
            model_name='game',
            name='client',
            field=models.CharField(blank=True, default='', max_length=49),
        ),
        migrations.AlterField(
            model_name='game',
            name='middle_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='midlle_title',
            field=models.CharField(blank=True, default='', max_length=49),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(blank=True, default='', max_length=49),
        ),
        migrations.AlterField(
            model_name='game',
            name='preview_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='promo_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='slogan',
            field=models.CharField(blank=True, default='', max_length=49),
        ),
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='game',
            name='top_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='top_description_italic',
            field=models.TextField(default=', blank=True'),
        ),
        migrations.AlterField(
            model_name='game',
            name='top_title',
            field=models.CharField(blank=True, default='', max_length=49),
        ),
        migrations.AlterField(
            model_name='game',
            name='video_id',
            field=models.CharField(blank=True, default='', max_length=49),
        ),
    ]
