# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20160427_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='bottom_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='bottom_title',
            field=models.CharField(blank=True, max_length=49),
        ),
        migrations.AlterField(
            model_name='game',
            name='client',
            field=models.CharField(blank=True, max_length=49),
        ),
        migrations.AlterField(
            model_name='game',
            name='middle_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='midlle_title',
            field=models.CharField(blank=True, max_length=49),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=49),
        ),
        migrations.AlterField(
            model_name='game',
            name='preview_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='promo_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='slogan',
            field=models.CharField(blank=True, max_length=49),
        ),
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='game',
            name='top_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='top_description_italic',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='top_title',
            field=models.CharField(blank=True, max_length=49),
        ),
        migrations.AlterField(
            model_name='game',
            name='video_id',
            field=models.CharField(blank=True, max_length=49),
        ),
    ]
