# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 14:39
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20160428_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screenshot',
            options={'ordering': ['the_order'], 'verbose_name': 'ScreenShot', 'verbose_name_plural': 'ScreenShot'},
        ),
        migrations.AddField(
            model_name='screenshot',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='game',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
        ),
    ]
