# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20160428_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['game_order'], 'verbose_name': 'Game', 'verbose_name_plural': 'Game objects'},
        ),
        migrations.AlterModelOptions(
            name='screenshot',
            options={'ordering': ['screenshot_order'], 'verbose_name': 'ScreenShot', 'verbose_name_plural': 'ScreenShot'},
        ),
        migrations.RenameField(
            model_name='game',
            old_name='the_order',
            new_name='game_order',
        ),
        migrations.RenameField(
            model_name='screenshot',
            old_name='the_order',
            new_name='screenshot_order',
        ),
    ]
