# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20160428_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=70)),
            ],
        ),
        migrations.AlterModelOptions(
            name='screenshot',
            options={'ordering': ['screenshot_order'], 'verbose_name': 'ScreenShot', 'verbose_name_plural': 'ScreenShots'},
        ),
    ]
