# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 14:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_topimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='promo_image',
        ),
        migrations.AddField(
            model_name='game',
            name='top_image',
            field=models.ImageField(default=datetime.datetime(2016, 5, 1, 14, 47, 54, 76319, tzinfo=utc), upload_to='games/top_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='preview_image',
            field=models.ImageField(upload_to='games/preview_images'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='screenshot_image',
            field=models.ImageField(upload_to='games/instance'),
        ),
    ]
