# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselobj',
            options={'ordering': ['the_order'], 'verbose_name': 'Инфо-блоки для карусели', 'verbose_name_plural': '1: Инфо-блоки для карусели'},
        ),
        migrations.AlterModelOptions(
            name='topvideo',
            options={'verbose_name': 'Видео-заставка', 'verbose_name_plural': '2: Видео-заставка'},
        ),
    ]
