# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/carousel_images', verbose_name='Image 1600x1066')),
                ('toptitle', models.CharField(blank=True, max_length=49, verbose_name='Top title')),
                ('middletitle', models.CharField(blank=True, max_length=49, verbose_name='Middle title')),
                ('bottomtitle', models.CharField(blank=True, max_length=49, verbose_name='Bottom title')),
                ('buttontitle', models.CharField(blank=True, max_length=49, verbose_name='Button lettering')),
                ('href', models.CharField(blank=True, max_length=49, verbose_name='Button href')),
                ('the_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Carousel object',
                'verbose_name_plural': 'Carousel objects',
                'ordering': ['the_order'],
            },
        ),
        migrations.CreateModel(
            name='TopVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=49)),
                ('slogan', models.CharField(blank=True, max_length=49)),
                ('video_id', models.CharField(blank=True, max_length=49)),
                ('button', models.CharField(blank=True, max_length=49)),
                ('href', models.CharField(blank=True, max_length=49)),
            ],
            options={
                'verbose_name': 'top video object',
                'verbose_name_plural': 'top video object',
            },
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
