# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20160508_0236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselobj',
            options={'ordering': ['the_order'], 'verbose_name': 'Для карусели', 'verbose_name_plural': 'Для карусели'},
        ),
        migrations.AlterModelOptions(
            name='topvideo',
            options={'verbose_name': 'Видео-заставка', 'verbose_name_plural': 'Видео-заставка'},
        ),
        migrations.AlterField(
            model_name='carouselobj',
            name='bottomtitle',
            field=models.CharField(blank=True, max_length=49, verbose_name='Нижняя надпись'),
        ),
        migrations.AlterField(
            model_name='carouselobj',
            name='buttontitle',
            field=models.CharField(blank=True, max_length=49, verbose_name='Надпись на кнопке'),
        ),
        migrations.AlterField(
            model_name='carouselobj',
            name='href',
            field=models.CharField(blank=True, max_length=49, verbose_name='Ссылка для кнопки'),
        ),
        migrations.AlterField(
            model_name='carouselobj',
            name='image',
            field=models.ImageField(upload_to='home/carousel_images', verbose_name='Картинка 1600x1066'),
        ),
        migrations.AlterField(
            model_name='carouselobj',
            name='middletitle',
            field=models.CharField(blank=True, max_length=49, verbose_name='Спедняя надпись(большая)'),
        ),
        migrations.AlterField(
            model_name='carouselobj',
            name='toptitle',
            field=models.CharField(blank=True, max_length=49, verbose_name='Верхняя надпись'),
        ),
    ]
