# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20160512_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topvideo',
            name='button',
            field=models.CharField(blank=True, max_length=49, verbose_name='Надпись на кнопке'),
        ),
        migrations.AlterField(
            model_name='topvideo',
            name='href',
            field=models.CharField(blank=True, max_length=49, verbose_name='Сылка кнопки'),
        ),
        migrations.AlterField(
            model_name='topvideo',
            name='slogan',
            field=models.CharField(blank=True, max_length=49, verbose_name='Девиз'),
        ),
        migrations.AlterField(
            model_name='topvideo',
            name='title',
            field=models.CharField(blank=True, max_length=49, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='topvideo',
            name='video_id',
            field=models.CharField(blank=True, max_length=49, verbose_name='Видео (код ютуба)'),
        ),
    ]
