# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_carousel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='img1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='img3',
        ),
    ]
