# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20160420_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='bottomtitle',
            field=models.CharField(default='', max_length=49),
        ),
        migrations.AddField(
            model_name='carousel',
            name='buttontitle',
            field=models.CharField(default='learn more', max_length=49),
        ),
        migrations.AddField(
            model_name='carousel',
            name='middletitle',
            field=models.CharField(default='', max_length=49),
        ),
        migrations.AddField(
            model_name='carousel',
            name='toptitle',
            field=models.CharField(default='/static/carousel_defoult.jpg', max_length=49),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to=''),
        ),
    ]
