# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20160421_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='bottomtitle',
            field=models.CharField(default='have fun, folks', max_length=49),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='buttontitle',
            field=models.CharField(default='', max_length=49),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(default='/static/carousel_defoult.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='middletitle',
            field=models.CharField(default='tabletcrushers', max_length=49),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='toptitle',
            field=models.CharField(default='game design company', max_length=49),
        ),
    ]
