# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20160421_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselobj',
            name='href',
            field=models.CharField(blank=True, max_length=49),
        ),
        migrations.AlterField(
            model_name='carouselobj',
            name='bottomtitle',
            field=models.CharField(blank=True, max_length=49),
        ),
        migrations.AlterField(
            model_name='carouselobj',
            name='buttontitle',
            field=models.CharField(blank=True, max_length=49),
        ),
        migrations.AlterField(
            model_name='carouselobj',
            name='middletitle',
            field=models.CharField(default='мастерская №8', max_length=49),
        ),
        migrations.AlterField(
            model_name='carouselobj',
            name='toptitle',
            field=models.CharField(blank=True, max_length=49),
        ),
    ]
