# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_topvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselobj',
            options={'ordering': ['the_order'], 'verbose_name': 'Carousel object', 'verbose_name_plural': 'Carousel objects'},
        ),
        migrations.AlterModelOptions(
            name='topvideo',
            options={'verbose_name': 'top video object', 'verbose_name_plural': 'top video object'},
        ),
        migrations.AddField(
            model_name='topvideo',
            name='button',
            field=models.CharField(blank=True, max_length=49),
        ),
        migrations.AddField(
            model_name='topvideo',
            name='href',
            field=models.CharField(blank=True, max_length=49),
        ),
    ]
