# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20160501_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselobj',
            name='bottomtitle',
            field=models.CharField(blank=True, max_length=49, verbose_name='Bottom title'),
        ),
        migrations.AlterField(
            model_name='carouselobj',
            name='buttontitle',
            field=models.CharField(blank=True, max_length=49, verbose_name='Button lettering'),
        ),
        migrations.AlterField(
            model_name='carouselobj',
            name='href',
            field=models.CharField(blank=True, max_length=49, verbose_name='Button href'),
        ),
        migrations.AlterField(
            model_name='carouselobj',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Image 1600x1066'),
        ),
        migrations.AlterField(
            model_name='carouselobj',
            name='middletitle',
            field=models.CharField(blank=True, max_length=49, verbose_name='Middle title'),
        ),
        migrations.AlterField(
            model_name='carouselobj',
            name='toptitle',
            field=models.CharField(blank=True, max_length=49, verbose_name='Top title'),
        ),
    ]
