# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20160501_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselobj',
            name='image',
            field=models.ImageField(upload_to='home/carousel_images', verbose_name='Image 1600x1066'),
        ),
    ]
