# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='middle_bg',
            field=models.ImageField(blank=True, upload_to='about/middle_bg', verbose_name='Фон под иконками достижений 1600x1066'),
        ),
    ]
