# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMetaTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70, verbose_name='Заголовок страницы (тэг <title>, до 70 символов)')),
                ('keywords', models.CharField(blank=True, max_length=210, verbose_name='Ключевые слова через запятую (тэг <keywords>, до 210 символов)')),
                ('description', models.CharField(blank=True, max_length=210, verbose_name='Описание (тэг <description>, до 210 символов)')),
            ],
            options={
                'verbose_name_plural': 'МетаТэги',
                'verbose_name': 'МетаТэги',
            },
        ),
    ]
