# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['member_order']},
        ),
        migrations.AddField(
            model_name='teammember',
            name='member_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
