# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/brands', verbose_name='Логотип')),
                ('brand_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['brand_order'],
                'verbose_name_plural': 'Логотипы',
                'verbose_name': 'Логотип',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/team_member_photos', verbose_name='Фотка 600x820')),
                ('name', models.CharField(max_length=49, verbose_name='Имя')),
                ('position', models.CharField(max_length=49, verbose_name='Должность')),
                ('member_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['member_order'],
                'verbose_name_plural': 'Сотрудники',
                'verbose_name': 'Сотрудник',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='about/client_avatars', verbose_name='Аватарка 100x100')),
                ('name', models.CharField(max_length=49, verbose_name='Имя')),
                ('speech', models.CharField(max_length=210, verbose_name='Слова')),
                ('member_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['member_order'],
                'verbose_name_plural': 'Отзывы',
                'verbose_name': 'Отзыв',
            },
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='about',
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['the_order'], 'verbose_name': 'Салон', 'verbose_name_plural': 'Салон'},
        ),
        migrations.RemoveField(
            model_name='about',
            name='preview_image',
        ),
        migrations.AddField(
            model_name='about',
            name='middle_bg',
            field=models.ImageField(default=1, upload_to='about/middle_bg', verbose_name='Фон под иконками достижений 1600x1066'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='promo_image',
            field=models.ImageField(default=1, upload_to='about/promo_image', verbose_name='Картинка (наши услуги) 1528x576'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='service_slogan',
            field=models.CharField(blank=True, max_length=420, verbose_name='Девиз услуг'),
        ),
        migrations.AddField(
            model_name='about',
            name='slogan',
            field=models.CharField(blank=True, max_length=420, verbose_name='Девиз'),
        ),
        migrations.AddField(
            model_name='about',
            name='team_slogan',
            field=models.CharField(blank=True, max_length=420, verbose_name='Девиз команды'),
        ),
        migrations.AddField(
            model_name='about',
            name='top_image',
            field=models.ImageField(default=1, upload_to='about/top_image', verbose_name='Верхняя картинка 1600x1067'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Заголовок'),
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.AddField(
            model_name='review',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.About'),
        ),
        migrations.AddField(
            model_name='member',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.About'),
        ),
        migrations.AddField(
            model_name='brand',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.About'),
        ),
    ]
