# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/brands', verbose_name='Logo')),
                ('brand_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['brand_order'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/team_member_photos', verbose_name='Member photo 600x820')),
                ('name', models.CharField(max_length=49)),
                ('position', models.CharField(max_length=49)),
                ('member_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Team member',
                'verbose_name_plural': 'Team members',
                'ordering': ['member_order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='about/client_avatars', verbose_name='Avatar 100x100')),
                ('name', models.CharField(max_length=49)),
                ('speech', models.CharField(max_length=210)),
                ('member_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Client review',
                'verbose_name_plural': 'Client reviews',
                'ordering': ['member_order'],
            },
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='about',
        ),
        migrations.RemoveField(
            model_name='about',
            name='preview_image',
        ),
        migrations.AddField(
            model_name='about',
            name='middle_bg',
            field=models.ImageField(default=1, upload_to='about/middle_bg', verbose_name='middle_bg 1600x1066'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='promo_image',
            field=models.ImageField(default=1, upload_to='about/promo_image', verbose_name='Promo image 1528x576'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='slogan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='top_image',
            field=models.ImageField(default=1, upload_to='about/top_image', verbose_name='Top image 1600x1067'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.AddField(
            model_name='review',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.About'),
        ),
        migrations.AddField(
            model_name='member',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.About'),
        ),
        migrations.AddField(
            model_name='brand',
            name='abjut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.About'),
        ),
    ]
