# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20160428_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['member_order'], 'verbose_name': 'TeamMember', 'verbose_name_plural': 'TeamMembers'},
        ),
        migrations.AddField(
            model_name='about',
            name='slogan',
            field=models.TextField(blank=True),
        ),
    ]
