# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20160508_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='slogan',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
