# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20160511_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['the_order'], 'verbose_name': 'Салон', 'verbose_name_plural': 'Салон'},
        ),
        migrations.AddField(
            model_name='about',
            name='service_slogan',
            field=models.CharField(blank=True, max_length=420, verbose_name='Девиз услуг'),
        ),
        migrations.AddField(
            model_name='about',
            name='team_slogan',
            field=models.CharField(blank=True, max_length=420, verbose_name='Девиз команды'),
        ),
        migrations.AlterField(
            model_name='about',
            name='middle_bg',
            field=models.ImageField(upload_to='about/middle_bg', verbose_name='Фон под иконками достижений 1600x1066'),
        ),
        migrations.AlterField(
            model_name='about',
            name='promo_image',
            field=models.ImageField(upload_to='about/promo_image', verbose_name='Картинка (наши услуги) 1528x576'),
        ),
        migrations.AlterField(
            model_name='about',
            name='slogan',
            field=models.CharField(blank=True, max_length=420, verbose_name='Девиз'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='about',
            name='top_image',
            field=models.ImageField(upload_to='about/top_image', verbose_name='Верхняя картинка 1600x1067'),
        ),
    ]
