# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 13:20
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20160518_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('ico_alias', models.CharField(blank=True, max_length=21, verbose_name='Код текстовой иконки(коды см. тут: http://rhythm.nikadevs.com/content/icons-et-line)')),
                ('ico_img', models.ImageField(blank=True, upload_to='about/services_ico', verbose_name='Иконка 80х80, ввместо текстовой иконки, если нужно')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='about',
            name='promo_image',
            field=models.ImageField(blank=True, upload_to='about/promo_image', verbose_name='Картинка (наши услуги) 1528x576'),
        ),
    ]
