# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20160501_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientreview',
            options={'ordering': ['member_order'], 'verbose_name': 'Client review', 'verbose_name_plural': 'Client reviews'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['member_order'], 'verbose_name': 'Team member', 'verbose_name_plural': 'Team members'},
        ),
        migrations.AlterField(
            model_name='about',
            name='preview_image',
            field=models.ImageField(upload_to='about/top_image', verbose_name='Top image 1600x1067'),
        ),
        migrations.AlterField(
            model_name='clientreview',
            name='avatar',
            field=models.ImageField(upload_to='about/client_avatars', verbose_name='Avatar 100x100'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to='about/team_member_photos', verbose_name='Member photo 600x820'),
        ),
    ]
