# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20160511_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['brand_order'], 'verbose_name': 'Логотип', 'verbose_name_plural': 'Логотипы'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['member_order'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='abjut',
            new_name='about',
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(upload_to='about/brands', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(upload_to='about/team_member_photos', verbose_name='Фотка 600x820'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=49, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(max_length=49, verbose_name='Должность'),
        ),
    ]
