# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20160518_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['s_order'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='service',
            name='about',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.About'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='s_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
