# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20160501_1747'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMember',
            new_name='Member',
        ),
    ]
