# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20160511_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['member_order'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='review',
            name='avatar',
            field=models.ImageField(upload_to='about/client_avatars', verbose_name='Аватарка 100x100'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=49, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='review',
            name='speech',
            field=models.CharField(max_length=210, verbose_name='Слова'),
        ),
    ]
