# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20160501_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='preview_image',
            new_name='top_image',
        ),
    ]
