# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_auto_20160502_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='middle_bg',
            field=models.ImageField(default=0, upload_to='about/middle_bg', verbose_name='middle_bg 1600x1066'),
            preserve_default=False,
        ),
    ]
