# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_auto_20160518_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='promo_top',
            field=models.CharField(blank=True, max_length=420, verbose_name='Верхняя надпись (блок с фоном под услугами. Если поля блока оставить пустыми, будет заставка со счетчиками)'),
        ),
    ]
