# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_auto_20160503_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='promo_image',
            field=models.ImageField(default=5, upload_to='about/promo_image', verbose_name='Promo image 1528x576'),
            preserve_default=False,
        ),
    ]
