# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_auto_20160518_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='promo_italic',
            field=models.CharField(blank=True, max_length=420, verbose_name='Наклонный текст (блок с фоном под услугами)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='promo_bottom',
            field=models.CharField(blank=True, max_length=140, verbose_name='Нижняя надпись (блок с фоном под услугами)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='promo_middle',
            field=models.CharField(blank=True, max_length=140, verbose_name='Центральная крупная надпись (блок с фоном под услугами)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='promo_top',
            field=models.CharField(blank=True, max_length=140, verbose_name='Верхняя надпись (блок с фоном под услугами. Если поля блока оставить пустыми, будет заставка со счетчиками)'),
        ),
    ]
