# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['brand_order'], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
